version: "3.7"
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - bond
  brb:
    image: xuqingfeng/brb:latest
    environment:
      - TGBOT_TOKEN=${TGBOT_TOKEN}
      - TGBOT_SOCKS5=${TGBOT_SOCKS5}
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=""
    ports:
      - "8000:8000"
    restart: always
    networks:
      - bond
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/data/redis"

networks:
  bond: