name: deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: deploy latest image to server
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /opt/brb && source .env && docker-compose pull && docker-compose up -d